[package]
name = "twitch_web_socket"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.1.1"
dotenv = "0.15.0"
futures-util = "0.3.31"
tokio = { version = "1.49.0", features = ["full"] }
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
